repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^apps/cortai-api/
      - id: ruff-format
        files: ^apps/cortai-api/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^apps/cortai-api/
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - sqlalchemy
